---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: canopy-evals-event-listener
spec:
  path: /
  to:
    kind: Service
    name: el-canopy-evals-event-listener
    weight: 100
  port:
    targetPort: http-listener
  tls:
    termination: edge
  wildcardPolicy: None
