# Llama Stack configuration
MODEL_NAME: "llama32"
MODEL_URL: "http://llama32:8000"


# ConfigMap for Llama Stack configuration
configMap:
  enabled: true

# OpenTelemetry Collector configuration
otelCollector:
  enabled: false

rag:
  enabled: false

mcp:
  enabled: false

eval:
  enabled: false


# MCP servers configuration
# mcpServers:
#   - name: "weather"
#     uri: "http://mcp-weather:80"
#     description: "Weather MCP Server for real-time weather data"
  # - name: "hr-api-tools"
  #   uri: "http://custom-mcp-server:80"
  #   description: "HR API MCP server with employee, vacation, job, and performance tools"
