apiVersion: v1
kind: Service
metadata:
  name: flipt
  labels:
    app: flipt
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: ui
    - port: 9000
      targetPort: 9000
      name: api
  selector:
    app: flipt