---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-persist
  labels:
    {{- include "llama-stack.labels" . | nindent 4 }}
  finalizers:
  - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem