---
apiVersion: v1
kind: Service
metadata:
  name: llama-stack
  labels:
    {{- include "llama-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8321
      protocol: TCP
      name: http
  selector:
    {{- include "llama-stack.selectorLabels" . | nindent 4 }}