kind: ConfigMap
apiVersion: v1
metadata:
  name: fms-orchestr8-config-nlp
data:
  config.yaml: |
  {{- if .Values.orchestrator_gateway.enabled }}
    openai: 
        service:
          hostname: llama-32-predictor.ai501.svc.cluster.local
          port: 8080
  {{- end }}
    detectors:
      regex_competitor:
        type: text_contents
        service:
            hostname: "127.0.0.1"
            port: 8080
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      hap:
        type: text_contents
        service:
          hostname: guardrails-detector-ibm-hap-predictor.ai501.svc.cluster.local
          port: 80
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      prompt_injection:
        type: text_contents
        service:
          hostname: prompt-injection-detector-predictor.ai501.svc.cluster.local
          port: 80
        chunker_id: whole_doc_chunker
        default_threshold: 0.5
      language_detection:
        type: text_contents
        service:
          hostname: language-detector-predictor.ai501.svc.cluster.local
          port: 80
        chunker_id: whole_doc_chunker
        default_threshold: 0.5