---
apiVersion: v1
kind: Service
metadata:
  name: guardrails-orchestrator
spec:
  selector:
    app: guardrails-orchestrator
    component: guardrails-orchestrator
  ports:
  - name: http
    port: 8080  
    targetPort: 8032 
  type: ClusterIP
{{- if .Values.orchestrator_gateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: guardrails-gateway
spec:
  selector:
    app: guardrails-orchestrator
    component: guardrails-orchestrator
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
{{- end }}
