{{ $password := .Values.password }}
{{- range $bucket := .Values.buckets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $bucket.name }}
  labels:
    opendatahub.io/dashboard: "true"
    opendatahub.io/managed: "true"
  annotations:
    opendatahub.io/connection-type: s3
    openshift.io/display-name: {{ $bucket.name }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ (split "-" $.Release.Namespace)._0 }}
  AWS_SECRET_ACCESS_KEY: {{ $password | default "thisisthepassword" }}
  AWS_DEFAULT_REGION: wonderland
  AWS_S3_ENDPOINT: http://minio-service.{{ $.Release.Namespace }}.svc.cluster.local:9000
  AWS_S3_BUCKET: {{ $bucket.name }}
{{- end }}