---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.USER_NAME }}-test-edit
  namespace: {{ .Values.USER_NAME }}-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.USER_NAME }}-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.USER_NAME }}-prod-edit
  namespace: {{ .Values.USER_NAME }}-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.USER_NAME }}-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.USER_NAME }}-tekton-image-pusher-rolebinding
  namespace: {{ .Values.USER_NAME }}-test
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Values.USER_NAME }}-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-pusher