# Llama Stack Operator Instance configuration
models:
  - name: "llama32"
    url: "http://llama-32-predictor.ai501.svc.cluster.local:8080/v1"

# Distribution configuration
distribution:
  image: "quay.io/rhoai-genaiops/odh-llama-stack-core-rhel9:rhoai-3.4-shields"


# ConfigMap for Llama Stack configuration
configMap:
  enabled: true

# Telemetry configuration
telemetry:
  enabled: true

rag:
  enabled: true
  milvus:
    service: "milvus"

mcp:
  enabled: false

mcp_aihub:
  enabled: false

otelCollector:
  enabled: false

guardrails:
  enabled: false

sealed_secrets:
  enabled: false